version: "3.7"

services:
  watchtower:
    container_name: watchtower
    image: watchtower
    build:
      context: ./
      dockerfile: Dockerfile
    
    volumes:
      - type: bind
        source: ./
        target: /app/.
    working_dir: /app
    command: poetry run python3 ./src/run_tests.py
             

    ports:
      - "8081:8081"
    env_file:
      - .env
    
    extra_hosts:
         - "host.docker.internal:host-gateway"



volumes:
  db_watchtower:
    driver: local


